openapi: 3.0.0
info:
  title: Node.js Starter API
  description: API documentation for Node.js Starter by Genius
  version: 1.0.0
servers:
  - url: http://localhost:5000/api
    description: Local server

paths:
  /auth/register:
    post:
      summary: Register a new user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, email, password]
              properties:
                username:
                  type: string
                  example: johndoe
                email:
                  type: string
                  example: johndoe@example.com
                password:
                  type: string
                  example: StrongPass123
      responses:
        "201":
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"

  /auth/login:
    post:
      summary: Login user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  example: johndoe@example.com
                password:
                  type: string
                  example: StrongPass123
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"

  /user/me:
    get:
      summary: Get logged-in user profile
      tags: [User]
      security: [ { bearerAuth: [] } ]
      responses:
        "200":
          description: User profile
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

    put:
      summary: Update user profile
      tags: [User]
      security: [ { bearerAuth: [] } ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Profile updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

  /dashboard:
    get:
      summary: Get dashboard data
      tags: [Dashboard]
      security: [ { bearerAuth: [] } ]
      responses:
        "200":
          description: Dashboard summary
          content:
            application/json:
              schema:
                type: object
                example:
                  stats:
                    users: 100
                    products: 50
                    revenue: 1200

  /products:
    get:
      summary: Get all products
      tags: [Products]
      responses:
        "200":
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"

    post:
      summary: Create a new product
      tags: [Products]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductInput"
      responses:
        "201":
          description: Product created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"

  /products/{id}:
    get:
      summary: Get a product by ID
      tags: [Products]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Product details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"

    put:
      summary: Update a product
      tags: [Products]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductInput"
      responses:
        "200":
          description: Product updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"

    delete:
      summary: Delete a product
      tags: [Products]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Product deleted

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          example: 123abc
        username:
          type: string
          example: johndoe
        email:
          type: string
          example: johndoe@example.com
        createdAt:
          type: string
          format: date-time

    AuthResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          $ref: "#/components/schemas/User"
        token:
          type: string
          example: jwt.token.here

    Product:
      type: object
      properties:
        id:
          type: string
          example: prod123
        name:
          type: string
          example: iPhone 15
        price:
          type: number
          example: 999.99
        description:
          type: string
          example: Latest iPhone model
        createdAt:
          type: string
          format: date-time

    ProductInput:
      type: object
      required: [name, price]
      properties:
        name:
          type: string
          example: iPhone 15
        price:
          type: number
          example: 999.99
        description:
          type: string
          example: Latest iPhone model